Module 1: Core concepts
bioN1ck/netflix-roulette pull request #1
Opened 2023-03-18 12:24 UTC by bioN1ck

2023-03-22 13:01 UTC, melk0sha requested changes

2023-03-22 13:01 UTC, melk0sha commented on src/App.tsx
> +class App extends React.Component {
It's better to use functional components in React:
https://react.dev/reference/react/Component#migrating-a-simple-component-from-a-class-to-a-function
https://react.dev/reference/react/Component#defining-a-class-component (see first "Pitfall")

Except of `Counter` component as it is a requirement to use class syntax

2023-03-22 13:01 UTC, melk0sha commented on src/App.tsx
> +    return <div className="App">
For CSS, there are naming conventions about classNames:
https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/

2023-03-22 13:01 UTC, melk0sha commented on src/components/ResultsFilter/ResultsFilter.tsx
> +  const checkActiveness = (genre: Genres): string => {
For such cases in future you can use one of the following packages that will help you to easy define customizible classNames:
https://www.npmjs.com/package/classnames
https://www.npmjs.com/package/clsx

2023-03-22 13:01 UTC, melk0sha commented on src/components/ResultsFilter/ResultsFilter.tsx
> +function ResultsFilter(props: ResultsFilterProps) {
I believe this component and the whole file should be named `GenreSelect`

2023-03-22 13:01 UTC, melk0sha commented on src/components/Search/Search.tsx
> +  const inputRef: MutableRefObject<HTMLInputElement | null> = useRef(null);
You can simply use here such typing:
` const inputRef = useRef<HTMLInputElement>(null);`

2023-03-22 13:05 UTC, melk0sha approved these changes

2023-03-22 13:13 UTC, melk0sha commented
Also, I don't know if you are using `Prettier` but I suggest you to install and use it as it saves time by code formatting. It can be managed to format by file saving

2023-03-22 13:28 UTC, melk0sha approved these changes

2023-03-23 07:29 UTC, bioN1ck commented on src/App.tsx
> +class App extends React.Component {
Fixed

2023-03-23 07:29 UTC, bioN1ck commented on src/App.tsx
> +    return <div className="App">
Switched to BEM

2023-03-23 07:29 UTC, bioN1ck commented on src/components/ResultsFilter/ResultsFilter.tsx
> +  const checkActiveness = (genre: Genres): string => {
Used the classnames pkg

2023-03-23 07:30 UTC, bioN1ck commented on src/components/ResultsFilter/ResultsFilter.tsx
> +function ResultsFilter(props: ResultsFilterProps) {
Fixed

2023-03-23 07:30 UTC, bioN1ck commented on src/components/Search/Search.tsx
> +  const inputRef: MutableRefObject<HTMLInputElement | null> = useRef(null);
Used proposed

2023-03-23 07:32 UTC, merged